# Generated by Django 3.2.15 on 2022-09-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_code',
            new_name='book_id',
        ),
    ]
